
package com.easylearnjava.consumer.webservice.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginInterface", targetNamespace = "http://webservice.provider.easylearnjava.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.easylearnjava.consumer.webservice.jaxws.UserWrapper
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.provider.easylearnjava.com/LoginInterface/getUserDetailsRequest", output = "http://webservice.provider.easylearnjava.com/LoginInterface/getUserDetailsResponse")
    public UserWrapper getUserDetails(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
