
package com.easylearnjava.consumer.webservice.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginImplementationService", targetNamespace = "http://webservice.provider.easylearnjava.com/", wsdlLocation = "http://localhost:8080/JAXWS-SOAP-MySQL-Login/login?wsdl")
public class LoginImplementationService
    extends Service
{

    private final static URL LOGINIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName LOGINIMPLEMENTATIONSERVICE_QNAME = new QName("http://webservice.provider.easylearnjava.com/", "LoginImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JAXWS-SOAP-MySQL-Login/login?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        LOGINIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public LoginImplementationService() {
        super(__getWsdlLocation(), LOGINIMPLEMENTATIONSERVICE_QNAME);
    }

    public LoginImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public LoginImplementationService(URL wsdlLocation) {
        super(wsdlLocation, LOGINIMPLEMENTATIONSERVICE_QNAME);
    }

    public LoginImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public LoginImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginInterface
     */
    @WebEndpoint(name = "LoginImplementationPort")
    public LoginInterface getLoginImplementationPort() {
        return super.getPort(new QName("http://webservice.provider.easylearnjava.com/", "LoginImplementationPort"), LoginInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginInterface
     */
    @WebEndpoint(name = "LoginImplementationPort")
    public LoginInterface getLoginImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.provider.easylearnjava.com/", "LoginImplementationPort"), LoginInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw LOGINIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return LOGINIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
