package com.easylearnjava.web;

import java.io.IOException;
import java.net.URL;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

import com.easylearnjava.consumer.webservice.jaxws.LoginInterface;
import com.easylearnjava.consumer.webservice.jaxws.User;
import com.easylearnjava.consumer.webservice.jaxws.UserWrapper;
import com.easylearnjava.exception.ServiceException;
import com.easylearnjava.util.Constants;

/**
 * 
 * @author rnr
 *
 *LoginServlet inherits all the features of a servlet by extending HttpServlet.
 *The doPost method will be called by the webContainer.
 *If valid credentials are given the user is redirected to success page.
 *If invalid credentials are entered then the login page is displayed back to the user.  
 */
public class LoginServlet extends HttpServlet{
		
	/**
	 * This is autogenerated
	 */
	private static final long serialVersionUID = 850900806199818086L;

	private static final String WS_URL = "http://localhost:8080/JAXWS-SOAP-MySQL-Login/login?wsdl";
	
	/**
	 * The request comes to this method when the login button is clicked
	 */
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		
		response.setContentType("text/html");
	
		try {
			//get the user entered input values from the "HttpServletRequest" object, i.e request 
			String userNameFromUI =  request.getParameter("usernameTB");
			String passwordFromUI =  request.getParameter("passwordTB");			
			
			//inputdata validation
			boolean isDataValid = isValidData(userNameFromUI, passwordFromUI);
			if(!isDataValid){
				request.setAttribute("errMsg", "username/password cannot be empty, must contain atleast 5 characters each");
				request.getRequestDispatcher("/login.jsp").forward(request, response);
				return;
			}
			
			URL url = new URL(WS_URL);
			QName qname = new QName("http://webservice.provider.easylearnjava.com/",	"LoginImplementationService");
			Service service = Service.create(url, qname);
			
			LoginInterface lInterface = service.getPort(LoginInterface.class);			
			UserWrapper userWrapper = (UserWrapper)lInterface.getUserDetails(userNameFromUI);
			
			if(userWrapper.getStatusId() > 0){
				User userObject = userWrapper.getUser();
				if(userObject.getUserPassword().equals(passwordFromUI)){
					request.setAttribute("reqName", userNameFromUI);
					request.getRequestDispatcher("/loginSuccess.jsp").forward(request, response);
				}else{
					request.setAttribute("errMsg", "invalid login cidentials");
					request.getRequestDispatcher("/login.jsp").forward(request, response);					
				}
			}else if(userWrapper.getStatusId() == 0){
				request.setAttribute("errMsg", Constants.GLOBAL_EXCEPTION_MESSAGE);
				request.getRequestDispatcher("/login.jsp").forward(request, response);
			}else{
				request.setAttribute("errMsg", "please register to login");
				request.getRequestDispatcher("/login.jsp").forward(request, response);					
			}
			
		}catch(Exception ex){
			if(!(ex instanceof ServiceException)){
				ex.printStackTrace();
			}
			request.setAttribute("errMsg", Constants.GLOBAL_EXCEPTION_MESSAGE);
			request.getRequestDispatcher("/login.jsp").forward(request, response);
		}
	}
	
	/**
	 * Method for validating the input values
	 * @param userName
	 * @param password
	 * @return
	 */
	public boolean isValidData(String userName, String password){
		
		if((null != userName) && (userName != "") && (userName.length() >= 5)){
			if((null != password) && (password != "") && (password.length() >= 5)){
				return true;
			}
		}		
		return false;		
	}	

}
